//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int IdComments { get; set; }
        public string Comments { get; set; }
        public int IdPeople { get; set; }
        public int IdRecord { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Record Record { get; set; }
    }
}
