//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Comments = new HashSet<Comment>();
            this.Records = new HashSet<Record>();
            this.Resourses = new HashSet<Resours>();
            this.Signs = new HashSet<Sign>();
        }
    
        public int IdPeople { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobilPhone { get; set; }
        public string EmailAddress { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int IdRole { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Record> Records { get; set; }
        public virtual ICollection<Resours> Resourses { get; set; }
        public virtual ICollection<Sign> Signs { get; set; }
    }
}
