//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resours
    {
        public int IdResourse { get; set; }
        public byte[] Resourse { get; set; }
        public Nullable<int> IdRecord { get; set; }
        public Nullable<int> IdPeople { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Record Record { get; set; }
    }
}
