//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sign
    {
        public int IdOwner { get; set; }
        public int IdSign { get; set; }
        public int Id { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
