//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme
    {
        public Theme()
        {
            this.Records = new HashSet<Record>();
        }
    
        public int IdTheme { get; set; }
        public string TitleOfTheme { get; set; }
    
        public virtual ICollection<Record> Records { get; set; }
    }
}
